services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=torifuku.kaiou@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - web

  elixir:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?SECRET_KEY_BASE must be provided}
      DATABASE_URL: ecto://postgres:postgres@db/toukon_ai_shogi
      PHX_HOST: toukon-ai-shogi.autoracex.dev
      PHX_SERVER: true
      VIRTUAL_HOST: toukon-ai-shogi.autoracex.dev
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: toukon-ai-shogi.autoracex.dev
      LETSENCRYPT_EMAIL: torifuku.kaiou@gmail.com
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - web
      - internal

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toukon_ai_shogi
    networks:
      - internal

volumes:
  certs:
  vhost:
  html:
  acme:
  postgres-data:

networks:
  web:
  internal:
