services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Ubuntu Version
        VARIANT: "ubuntu-24.04"
        # User
        USERNAME: "vscode"
        # Elixir Version
        ELIXIR_VERSION: "1.18.4"
        # OTP release
        ELIXIR_OTP_RELEASE: "27"
        # OTP Version
        OTP_VERSION: "27.3.4.3"
        # Phoenix Version
        PHOENIX_VERSION: "1.8.1"

    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  postgres-data: