import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :toukon_ai_shogi, ToukonAiShogiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Keep Swoosh Local Memory Storage enabled so we can reuse the dev mailbox in prod for now
config :swoosh, local: true

# Expose the mailbox preview routes in production to inspect emails
config :toukon_ai_shogi, mailbox_routes: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
